version: '3.8'

services:
  web:
    build: .
    container_name: weshare-web
    ports:
      - "9090:9090"
    volumes:
      - ./public:/app/public
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
